### ISSUE TITLE
rtorrent-rpc-0.2.1.0 doesn't compile with GHC 7.8.4

### ISSUE THREAD

**Issue by peti** [megantti/rtorrent-rpc#1]
See http://hydra.cryp.to/build/590494/log/raw for a complete build log that shows the error we saw in our CI environment.

**Comment by peti** [comment]
Why did you close the issue?

**Comment by megantti** [comment]
The package is now updated to be compatible with newer Haxr, since it switched to use ExpectT instead of ErrorT.
